server.port=8080

spring.application.name=products-api

# Disable database auto configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Logging level
logging.level.org.springframework=INFO
logging.level.com.example=DEBUG

# Show SQL queries in console (optional)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
