pipeline {
    agent any
    
    tools{
        maven "maven"
    }    

    stages {

        stage('Git Clone') {
            steps {
               git branch: 'main', url: 'https://github.com/AFSAL790/DevOpsProject2.git'
            }
        }

        stage('Maven Build'){
            steps{
                dir('01_products_api'){
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Docker Image'){
            steps{
                dir('01_products_api'){
                    sh 'docker build -t afsal790/products_api .'
                }
            }
        }

        stage('Docker Image push'){
            steps{
                withCredentials([usernamePassword(credentialsId: 'docker_pwd', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'docker login -u $DOCKER_USER -p $DOCKER_PASS'
                    sh 'docker push afsal790/products_api'
                }
            }
        }

        stage('k8s deployment'){
            steps{
                dir('01_products_api'){
                    sh 'kubectl apply -f Deployment.yml'
                }
            }
        }
    }
}
